dist: xenial
language: python
python:
  - 3.5
  - 3.6
  - 3.7
env:
  - DJANGO_VERSION='>=2.0,<2.1'
  - DJANGO_VERSION='>=2.1,<2.2'
  - DJANGO_VERSION='==2.2b1'
script: make test DJANGO_VERSION=$DJANGO_VERSION
branches:
  only:
    - unstable
    - master
